{
  description = "Zallet — reproducible static-musl builds (amd64 + arm64)";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    crane.url = "github:ipetkov/crane/v0.20.3";
    rust-overlay = { url = "github:oxalica/rust-overlay"; inputs.nixpkgs.follows = "nixpkgs"; };
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, crane, rust-overlay, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; overlays = [ (import rust-overlay) ]; };
        muslTarget =
          if system == "aarch64-linux" then "aarch64-unknown-linux-musl"
          else "x86_64-unknown-linux-musl";
        # cargo reads the per-target env var named after the UPPERCASED triple
        # with -/. → _ (e.g. CC_x86_64_unknown_linux_musl). Derive it from the
        # active target so BOTH arches get the musl-clang toolchain — hardcoding
        # the aarch64 name left x86_64-on-x86 builds without a CC for the *-sys
        # crates.
        targetEnvSuffix =
          builtins.replaceStrings [ "-" "." ] [ "_" "_" ] muslTarget;
        rustToolchain = pkgs.rust-bin.stable."1.88.0".default.override {
          targets = [ muslTarget ];
        };
        craneLib = (crane.mkLib pkgs).overrideToolchain rustToolchain;
        # craneLib.filterCargoSources only recognises Cargo.toml/Cargo.lock
        # files that belong to the ROOT workspace's resolution graph. Since
        # zcash/zallet#540, backends/zebra and backends/zaino are each their
        # own workspace (excluded from the root Cargo.toml's `[workspace]`),
        # so filterCargoSources silently drops their Cargo.lock files from the
        # filtered $src — Cargo.toml and src/ survive (matched generically),
        # but Cargo.lock does not. `replaceCargoLockHook`'s `replaceCargoLock`
        # then has no backends/*/Cargo.lock to move aside, and instead
        # clobbers the ROOT Cargo.lock with the backend's lockfile content,
        # leaving Cargo unable to resolve backends/zaino's git-patched `age`
        # dependency correctly ("requires a lock file to be present first").
        # Explicitly keep every backends/*/Cargo.lock (and Cargo.toml, for
        # symmetry/robustness) regardless of what filterCargoSources decides.
        isBackendCargoFile = path:
          (builtins.match ".*/backends/[^/]+/Cargo\\.(toml|lock)$" path != null);
        ftlOrCargo = path: type:
          (builtins.match ".*\\.ftl$" path != null)
          || (builtins.match ".*/i18n\\.toml$" path != null)
          || (isBackendCargoFile path)
          || (craneLib.filterCargoSources path type);
        src = pkgs.lib.cleanSourceWith { src = ./.; filter = ftlOrCargo; name = "source"; };
        # The *-sys C/C++ deps need a coherent musl toolchain. pkgsMusl.clangStdenv.cc
        # is a clang targeting aarch64-musl with libc++ — this resolves a two-sided
        # conflict that ad-hoc cc choices can't:
        #   * pqcrypto/pqclean (C): its compat.h does `#include <features.h>` only
        #     when `!defined(__clang__)`; clang defines __clang__ so it skips that
        #     glibc-only header (gcc would pull it and fail to compile under musl).
        #   * zcash_script (C++): clangStdenv links LLVM libc++ built against musl,
        #     instead of gcc's libstdc++ which references glibc-only symbols
        #     (__libc_single_threaded, __cxa_thread_atexit_impl) that break the
        #     static-musl link.
        # This mirrors how StageX's pre-integrated clang+libc++ pallet works on amd64.
        clangCC = pkgs.pkgsMusl.clangStdenv.cc;
        # Build one of the binaries Zallet ships. Since zcash/zallet#540 each
        # chain backend lives in its own cargo workspace with its own lockfile
        # (backends/zebra → zallet-zebra, backends/zaino → zallet-zaino),
        # and the user-facing `zallet` binary is a thin launcher in the root
        # workspace that dispatches to whichever backend binary the config
        # names. `manifestDir` selects the workspace; the generated share tree
        # (completions/manpages) is emitted by zallet-core's build script and
        # collected once, from the zebra-state backend build.
        #
        # NOTE: the nix outputs do NOT include debian-copyright — it is the
        # union of all three graphs and is generated by `gen-copyright` on the
        # StageX (amd64) path; the license inventory is arch-independent, so
        # the release workflow reuses the amd64 copy for the arm64 deb.
        mkZallet = { manifestDir ? null, binName, features ? [ ], collectShare ? false }:
          craneLib.buildPackage ({
          inherit src;
          pname = binName;
          version = (craneLib.crateNameFromCargoToml {
            cargoToml =
              if manifestDir == null then ./zallet/Cargo.toml
              else ./. + "/${manifestDir}/Cargo.toml";
          }).version;
          strictDeps = true;
          cargoLock =
            if manifestDir == null then ./Cargo.lock
            else ./. + "/${manifestDir}/Cargo.lock";
          cargoExtraArgs = "--locked --bin ${binName}"
            + pkgs.lib.optionalString (manifestDir != null)
                " --manifest-path ${manifestDir}/Cargo.toml"
            + pkgs.lib.optionalString (features != [ ])
                " --features ${pkgs.lib.concatStringsSep "," features}";
          # crane's mkDummySrc (used for the deps-only derivation that
          # buildPackage builds internally to cache dependency compilation)
          # ALWAYS copies the `cargoLock` argument to the dummy tree's ROOT as
          # `$out/Cargo.lock` — it has no concept of a lockfile living in a
          # workspace subdirectory (see crane's lib/mkDummySrc.nix,
          # `copyCargoLock`). backends/zaino and backends/zebra are each their
          # own `[workspace]` (excluded from the root Cargo.toml), so Cargo
          # looks for the lockfile NEXT TO `--manifest-path
          # ${manifestDir}/Cargo.toml`, not at the tree root. Without this,
          # `cargo check --manifest-path backends/zaino/Cargo.toml` finds no
          # lockfile in that directory and cannot resolve backends/zaino's
          # git-patched `age` dependency ("requires a lock file to be present
          # first"). replaceCargoLockHook (a prePatchHook) has already placed
          # the right content at the tree root by the time postPatch runs, in
          # BOTH the dummy deps-only build and the real build — so just copy
          # root Cargo.lock into the workspace subdirectory Cargo actually
          # reads from.
          postPatch = pkgs.lib.optionalString (manifestDir != null) ''
            cp Cargo.lock ${manifestDir}/Cargo.lock
          '';
          CARGO_BUILD_TARGET = muslTarget;
          # crane's `installFromCargoBuildLogHook` registers a POSTBUILD hook
          # (not an install-phase one — overriding installPhaseCommand does
          # NOT skip it) that runs `cargo metadata --format-version 1` with NO
          # --manifest-path, resolving against the tree-root workspace
          # (zallet-core, zallet, tools/gen-copyright), not
          # backends/${manifestDir}. `cargo metadata` resolves
          # dev-dependencies too, and zallet-core's dev-deps (proptest,
          # trycmd, ...) were never vendored for backends/zaino's or
          # backends/zebra's independent lockfile/vendor dir (zcash/zallet#540
          # deliberately decouples the three resolution graphs) — so that
          # metadata call fails ("no matching package found: proptest"),
          # which corrupts the hook's downstream jq invocation ("unexpected
          # '|'") with a confusing error that hides the real failure above it.
          # `doNotPostBuildInstallCargoBinaries` is the hook's own documented
          # escape hatch (see its setup-hook script) — set it and install the
          # already-built binary ourselves from cargo's well-known --target
          # output path instead.
          doNotPostBuildInstallCargoBinaries = manifestDir != null;
          # Static musl; use the musl clang as the linker so libc++ + crt resolve
          # coherently (a generic cc-wrapper mis-targets gnu vs musl here).
          CARGO_BUILD_RUSTFLAGS = "-C target-feature=+crt-static -C codegen-units=1 -C linker=${clangCC}/bin/cc -C link-arg=-static";
          nativeBuildInputs = with pkgs; [ protobuf llvmPackages.clang pkg-config git ];
          LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
          PROTOC = "${pkgs.protobuf}/bin/protoc";
          doCheck = false;
          # zallet/build.rs (clap_complete + clap_mangen) emits completions,
          # manpages and debian-copyright into target/<triple>/release/{completions,
          # manpages} + debian-copyright. crane installs only the binary, so copy
          # those generated assets into $out/share/zallet — the deb matrix +
          # the StageX export layout expect them there. Only the default
          # (zebra-state) binary carries the share tree + keeps the `zallet` name.
          postInstall = pkgs.lib.optionalString collectShare ''
            # build.rs writes completions/ + manpages/ into the cargo target dir
            # (derived from OUT_DIR's 4th ancestor → <target>/<triple>/release).
            # crane's CARGO_TARGET_DIR isn't necessarily ./target, so SEARCH for
            # the generated dirs rather than assuming a fixed path — a fixed
            # `target/<triple>/release` silently missed them under crane, which
            # left the .deb step globbing for completions/zallet.bash and failing.
            mkdir -p "$out/share/zallet"
            comp="$(find . -type d -name completions -path '*release*' 2>/dev/null | head -1)"
            mans="$(find . -type d -name manpages    -path '*release*' 2>/dev/null | head -1)"
            if [ -n "$comp" ]; then cp -r "$comp" "$out/share/zallet/completions"; else
              echo "postInstall: completions/ not found under target tree" >&2; exit 1; fi
            if [ -n "$mans" ]; then cp -r "$mans" "$out/share/zallet/manpages"; fi
          '';
        }
        # Per-target CC/CXX for the *-sys crates' cc-rs, keyed by the active
        # triple (CC_x86_64_unknown_linux_musl on amd64, CC_aarch64_... on arm64).
        // {
          "CC_${targetEnvSuffix}" = "${clangCC}/bin/cc";
          "CXX_${targetEnvSuffix}" = "${clangCC}/bin/c++";
        }
        # With `--manifest-path ${manifestDir}/Cargo.toml`, Cargo resolves the
        # default target dir relative to THAT workspace's root
        # (${manifestDir}/target/...), not the build's $PWD (the tree root)
        # — but crane's installCargoArtifactsHook looks for $CARGO_TARGET_DIR
        # (defaulting to plain `target`) at $PWD, so it can't find anything
        # to install ("cd: target: No such file or directory") once a
        # manifestDir is involved. Pin it explicitly so both Cargo and the
        # hook agree on one absolute location. Only for manifestDir != null:
        # the launcher (manifestDir == null) already worked correctly with
        # crane's own default before this was added, and forcing the same
        # value onto it broke its unrelated, working install path
        # (stripRustToolchain ran before $out existed).
        // pkgs.lib.optionalAttrs (manifestDir != null) {
          CARGO_TARGET_DIR = "target";
          # See the doNotPostBuildInstallCargoBinaries comment above: install
          # the already-built binary ourselves. Only set for manifestDir !=
          # null — omitting the attribute (not just emptying its value) for
          # the launcher is required for crane's own default
          # `installPhaseCommand` (the one that moves
          # $postBuildInstallFromCargoBuildLogOut to $out) to take effect via
          # its `args.installPhaseCommand or <default>` fallback; an explicit
          # `""` here would override that default with a no-op and $out would
          # never be created, and the postInstall toolchain-stripping hook
          # would fail with "No such file or directory".
          installPhaseCommand = ''
            mkdir -p $out/bin
            cp target/${muslTarget}/release/${binName} $out/bin/${binName}
          '';
        });
        # The zebra-state backend binary owns the completions/manpages share
        # tree that the deb + StageX export consume (both backends generate
        # identical trees; one copy suffices).
        zallet-zebra = mkZallet {
          manifestDir = "backends/zebra";
          binName = "zallet-zebra";
          features = [ "rpc-cli" "zcashd-import" ];
          collectShare = true;
        };
        zallet-zaino = mkZallet {
          manifestDir = "backends/zaino";
          binName = "zallet-zaino";
          features = [ "rpc-cli" "zcashd-import" ];
        };
        # The user-facing launcher (root workspace): dispatches to the backend
        # binary named by the config's `backend` key, installed next to itself.
        zallet-launcher = mkZallet { binName = "zallet"; };
        # Everything the runtime image layout carries, merged: the launcher and
        # both backends side by side, plus the share tree.
        zallet = pkgs.symlinkJoin {
          name = "zallet";
          paths = [ zallet-launcher zallet-zebra zallet-zaino ];
        };
      in {
        packages.default = zallet;
        packages.zallet = zallet;
        packages.zallet-launcher = zallet-launcher;
        packages.zallet-zebra = zallet-zebra;
        packages.zallet-zaino = zallet-zaino;
      });
}
